### ISSUE TITLE
Not compatible with Node v6.2.2

### ISSUE THREAD

**Issue by polyrhythmatic** [justinlatimer/node-midi#111]
Installing with Node v6.2.2 

`npm install midi`

gives the following error in node-gyp

`In file included from ../src/node-midi.cpp:1:
../node_modules/nan/nan.h:590:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:596:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:601:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../node_modules/nan/nan.h:607:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/midi/src/node-midi.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/sethkranzler/.nvm/versions/node/v6.2.2/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.4.0
gyp ERR! command "/Users/sethkranzler/.nvm/versions/node/v6.2.2/bin/node" "/Users/sethkranzler/.nvm/versions/node/v6.2.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sethkranzler/Development/app/node_modules/midi
gyp ERR! node -v v6.2.2
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
p5js-connect@1.0.0 /Users/sethkranzler/Development/app
├── abbrev@1.0.9 
├── fstream@1.0.10 
├── glob@7.0.4 
├── npm-package-arg@4.2.0 
├── npm-user-validate@0.1.4 
├── readable-stream@2.1.4 
├── which@1.2.10 
└── wrappy@1.0.2 

npm ERR! Darwin 15.4.0
npm ERR! argv "/Users/sethkranzler/.nvm/versions/node/v6.2.2/bin/node" "/Users/sethkranzler/.nvm/versions/node/v6.2.2/bin/npm" "install" "midi"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! midi@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the midi@0.9.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the midi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs midi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls midi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sethkranzler/Development/app/npm-debug.log
`
I then switched to Node 4.4.2 and was able to install with no issues.

Unfortunately anything below node 6.x.x will not work for my application since I am building an electron app with its own compilation issues. It would be great to use this library, any ideas on how to get it to work with node 6.2.2?

**Comment by drewish** [comment]
yeah sorry this was fixed in master but hadn't been released. t just published a new 0.9.5 release, please use that.
