### ISSUE TITLE
using midi in electron

### ISSUE THREAD

**Issue by abulka** [justinlatimer/node-midi#113]
I finally got this midi library running in [electron](http://electron.atom.io/) by running the `./node_modules/.bin/electron-rebuild` tool which I think does a `node-gyp rebuild` against the version of node that electron uses.  However now I cannot import midi into regular node - I describe the problem here.
https://github.com/electron/electron-rebuild/issues/103
Can anyone think of a way around this?  I think it has to do with the fact that this midi library involves a `node-gyp rebuild` step against two different versions of node? (despite the fact that my regular node and the electron node version report apparent;y as the same v6.3.0).

**Comment by MarshallOfSound** [comment]
@abulka I'll reply here as well because I'm an amazing person 😆 \

> (despite the fact that my regular node and the electron node version report apparent;y as the same v6.3.0).

Although they use the same core node version, they are two very different node builds.  Electron-rebuild doesn't rebuild against a different node version, it rebuilds against Electron's node headers.

**Comment by abulka** [comment]
See solution https://github.com/electron/electron-rebuild/issues/103

**Comment by FireController1847** [comment]
I can't seem to understand that question (being a beginner electron user). What exactly do I need to do to fix this? I don't think this is a seperate issue, but here is my error.
```js
E:\Development\Electron\MPPA\node_modules\bindings\bindings.js:83 Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\E:\Development\Electron\MPPA\node_modules\midi\build\Release\midi.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at bindings (E:\Development\Electron\MPPA\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (E:\Development\Electron\MPPA\node_modules\midi\midi.js:1:186)
```
