### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by KScottDB** [justinlatimer/node-midi#149]
```gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\ScottBeebiWan\Desktop\code\skmid\node_modules\midi
gyp ERR! node -v v10.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN discord-rpc@3.1.0 requires a peer of register-scheme@github:devsnek/node-register-scheme but none is installed. You must install peer dependencies yourself.
npm WARN skmid@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! midi@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the midi@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ScottBeebiWan\AppData\Roaming\npm-cache\_logs\2019-09-20T07_51_06_601Z-debug.log```

**Comment by KScottDB** [comment]
i was hesitant to post this in node gyp issues because it said a problem with (interpreted as _involving_) installing a specific package should be posted in the package's repository.
