### ISSUE TITLE
Please Support aarch64(Android)

### ISSUE THREAD

**Issue by Zel9278** [justinlatimer/node-midi#150]
I tried to use this module on Android, but it fails with the following error

```
$ npm i midi

> midi@1.0.0 install /data/data/com.termux/files/home/node_modules/midi
> node-gyp rebuild

make: Entering directory '/data/data/com.termux/files/home/node_modules/midi/build'
  CXX(target) Release/obj.target/midi/src/lib/RtMidi/RtMidi.o
../src/lib/RtMidi/RtMidi.cpp:439:3: error: cannot use 'throw' with exceptions disabled
  throw( RtMidiError( errorText, RtMidiError::UNSPECIFIED ) );
  ^
../src/lib/RtMidi/RtMidi.cpp:506:3: error: cannot use 'throw' with exceptions disabled
  throw( RtMidiError( errorText, RtMidiError::UNSPECIFIED ) );
  ^
../src/lib/RtMidi/RtMidi.cpp:557:5: error: cannot use 'throw' with exceptions disabled
    throw RtMidiError( errorString, type );
    ^

3 errors generated.
make: *** [midi.target.mk:108: Release/obj.target/midi/src/lib/RtMidi/RtMidi.o] Error 1
make: Leaving directory '/data/data/com.termux/files/home/node_modules/midi/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.9.112-16365652
gyp ERR! command "/data/data/com.termux/files/usr/bin/node" "/data/data/com.termux/files/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /data/data/com.termux/files/home/node_modules/midi
gyp ERR! node -v v12.10.0
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/data/data/com.termux/files/home/package.json'
npm WARN home No description
npm WARN home No repository field.
npm WARN home No README data
npm WARN home No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! midi@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the midi@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2019-09-23T00_42_51_910Z-debug.log
```

**Comment by justinlatimer** [comment]
Looks like you're attempting to compile with exceptions disabled. `RtMidi`, the underlying library `node-midi` uses requires exceptions so you'll need to enabled them in your environment.
