### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by wolfy01** [justinlatimer/node-midi#154]
```$ npm i midi

> ref@1.3.5 install C:\Users\wolfy.DESKTOP-0QI782C\downloads\mpp\mpp2vc-master\mpp2vc-master\node_modules\ref
> node-gyp rebuild


C:\Users\wolfy.DESKTOP-0QI782C\downloads\mpp\mpp2vc-master\mpp2vc-master\node_modules\ref>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\wolfy.DESKTOP-0QI782C\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\wolfy.DESKTOP-0QI782C\downloads\mpp\mpp2vc-master\mpp2vc-master\node_modules\ref
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> midi@1.0.0 install C:\Users\wolfy.DESKTOP-0QI782C\downloads\mpp\mpp2vc-master\mpp2vc-master\node_modules\midi
> node-gyp rebuild


C:\Users\wolfy.DESKTOP-0QI782C\downloads\mpp\mpp2vc-master\mpp2vc-master\node_modules\midi>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\wolfy.DESKTOP-0QI782C\AppData\Local\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\wolfy.DESKTOP-0QI782C\downloads\mpp\mpp2vc-master\mpp2vc-master\node_modules\midi
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 (node_modules\ref):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ref@1.3.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! midi@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the midi@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wolfy.DESKTOP-0QI782C\AppData\Roaming\npm-cache\_logs\2019-11-15T04_42_21_899Z-debug.log
```

**Comment by wolfy01** [comment]
I also tried installing directly from the source, which also had a very similar error.

**Comment by maartenverheul** [comment]
This issue is not related to this library, but to your installation of node-gyp (node ​​is trying to use python). I have solved this issue for myself in the past, which I don't know how anymore.

**Comment by wolfy01** [comment]
well thats not very helpful

**Comment by XanderCodes** [comment]
I'm getting this exact same error, does someone know how to fix node-gyp?

**Comment by maartenverheul** [comment]
> I'm getting this exact same error, does someone know how to fix node-gyp?

Can you tell how to reproduce it?

**Comment by bluelotusmedia** [comment]
I have this same error when running npm install midi

**Comment by maartenverheul** [comment]
I searched a bit, and this is what I found:

https://github.com/nodejs/node-gyp/issues/1528#issuecomment-413507902

You should be using python 2 instead of python 3. Set the correct python path in your computer, and then check it using ```python --version```

**Comment by martinberlin** [comment]
Best solution I found [is this one](https://stackoverflow.com/a/40815111/3886804).


You can install gyp module by pip with following command:

pip install git+https://chromium.googlesource.com/external/gyp


NOTE: That I switched to Python 2.7.18 using pyenv before but I'm not sure if that's essential. Just followed this entry and installed this using pip instead of NPM
