### ISSUE TITLE
DLL init failure in Electron

### ISSUE THREAD

**Issue by TesseraSkye** [justinlatimer/node-midi#172]
Trying to get the midi library to run in Electron, I've been unsuccessful thus far. upon trying to import the module, I receive an error stating:

`Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\_PROJECTPATH_\node_modules\midi\build\Release\midi.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at bindings (_PROJECTPATH_\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (_PROJECTPATH_\node_modules\midi\midi.js:1:186)`

I've called electron-build to try and fix an mismatch in node version, and it doesn't seem to have helped any.

**Comment by m9dfukc** [comment]
To fix the version mismatch you need to rebuild node-midi via https://github.com/electron/electron-rebuild
