### ISSUE TITLE
Unable to rebuild midi

### ISSUE THREAD

**Issue by RichardFoss** [justinlatimer/node-midi#229]
Hi, thanks for this MIDI module! I am having difficulty rebuilding it on a new MacBook. Any ideas would be much appreciated! I do have the Xcode developer command line tools installed - xcode-select -p gives me - /Library/Developer/CommandLineTools

Here is the rebuild and subsequent output:

csrf@AdminisatorsMBP midi % nw-gyp rebuild --target=0.41.3 --arch=x64
gyp info it worked if it ends with ok
gyp info using nw-gyp@3.6.6
gyp info using node@12.13.0 | darwin | x64
gyp info spawn /Library/Frameworks/Python.framework/Versions/2.7/bin/python2
gyp info spawn args [
gyp info spawn args   '/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/csrf/Documents/Git-Repos/ImmerGo-Presonus-SL/immergo-presonus-sl/node_modules/midi/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/csrf/.nw-gyp/0.41.3/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/csrf/.nw-gyp/0.41.3',
gyp info spawn args   '-Dnode_gyp_dir=/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp',
gyp info spawn args   '-Dnode_lib_file="/Users/csrf/.nw-gyp/0.41.3/<(target_arch)/node.lib"',
gyp info spawn args   '-Dnw_lib_file="/Users/csrf/.nw-gyp/0.41.3/<(target_arch)/nw.lib"',
gyp info spawn args   '-Dmodule_root_dir=/Users/csrf/Documents/Git-Repos/ImmerGo-Presonus-SL/immergo-presonus-sl/node_modules/midi',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '-Dv13=1',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Traceback (most recent call last):
  File "/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp/gyp/gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp/gyp/pylib/gyp/generator/make.py", line 2170, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp/gyp/pylib/gyp/generator/make.py", line 795, in Write
    self.Pchify))
  File "/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp/gyp/pylib/gyp/generator/make.py", line 1190, in WriteSources
    cflags = self.xcode_settings.GetCflags(configname)
  File "/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp/gyp/pylib/gyp/xcode_emulation.py", line 551, in GetCflags
    archs = self.GetActiveArchs(self.configname)
  File "/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp/gyp/pylib/gyp/xcode_emulation.py", line 420, in GetActiveArchs
    xcode_archs_default = GetXcodeArchsDefault()
  File "/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp/gyp/pylib/gyp/xcode_emulation.py", line 118, in GetXcodeArchsDefault
    xcode_version, _ = XcodeVersion()
  File "/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1265, in XcodeVersion
    version = re.match(r'(\d\.\d\.?\d*)', version).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/csrf/.nvm/versions/node/v12.13.0/lib/node_modules/nw-gyp/lib/configure.js:367:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 21.6.0
gyp ERR! command "/Users/csrf/.nvm/versions/node/v12.13.0/bin/node" "/Users/csrf/.nvm/versions/node/v12.13.0/bin/nw-gyp" "rebuild" "--target=0.41.3" "--arch=x64"
gyp ERR! cwd /Users/csrf/Documents/Git-Repos/ImmerGo-Presonus-SL/immergo-presonus-sl/node_modules/midi
gyp ERR! node -v v12.13.0
gyp ERR! nw-gyp -v v3.6.6
gyp ERR! not ok

**Comment by RichardFoss** [comment]
Solved by installing the complete Xcode, not just command line tools!
