### ISSUE TITLE
'Error: %1 is not a valid Win32 application' under Node-Webkit/Windows 7

### ISSUE THREAD

**Issue by ttaluy** [justinlatimer/node-midi#53]
Dear all,

I have tried to use node-midi under node-webkit, but when I try to execute this simple script:

	var midi = require('midi');
	var input = new midi.input();

	window.onload = function() {
		console.log(input.getPortCount());
	}

I get the following error:

	Error: %1 is not a valid Win32 application. 
	c:\Users\ttaluy\AppData\Local\Temp\nw2524_20403\node_modules\midi\build\Release\midi.node
	    at Module.load (module.js:352:32)
	    at Function.Module._load (module.js:308:12)
	    at Module.require (module.js:360:17)
	    at require (module.js:376:17)
	    at bindings (C:\Users\ttaluy\AppData\Local\Temp\nw2524_20403\node_modules\midi\node_modules\bindings\bindings.js:76:44)
	    at Object.eval (C:\Users\ttaluy\AppData\Local\Temp\nw2524_20403\node_modules\midi\midi.js:1:93)
	    at Module._compile (module.js:452:26)
	    at Object.Module._extensions..js (module.js:470:10)
	    at Module.load (module.js:352:32)
	    at Function.Module._load (module.js:308:12)

It looks like this is a path-related issue, maybe a path having empty spaces or something not being interpreted correctly under Microsoft Windows? I am using Windows 7 Ultimate SP1 64-bit with node-webkit-v0.9.2, Python 2.7.7 and Visual C++. I had a couple of warnings during the installation through npm, I did not note these down, but they can be easily reproduced in case you need them.

Thank you!

**Comment by drewish** [comment]
I think the switch to using NAN and the fix for https://github.com/justinlatimer/node-midi/pull/63 should have solved this. I'm going to close. If there are still problems post a comment and I'll reopen it.
