### ISSUE TITLE
Error installing via npm

### ISSUE THREAD

**Issue by met5678** [justinlatimer/node-midi#90]
Hey, I've previously installed this package with no problems, but I can't seem to install it anymore. Neither the latest version or version 0.9.3 (which used to install fine) work. I tried before and after upgrading node from 0.11.x to 4.2.2 and the same error occurs each time. Here's the log:

```
gyp info spawn make
gyp info spawn args [ 'V=1', 'BUILDTYPE=Release', '-C', 'build' ]
  c++ '-DNODE_GYP_MODULE_NAME=midi' '-D_DARWIN_USE_64_BIT_INODE=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__MACOSX_CORE__' '-DBUILDING_NODE_EXTENSION' -I/Users/andrew/.node-gyp/4.2.2/include/node -I/Users/andrew/.node-gyp/4.2.2/src -I/Users/andrew/.node-gyp/4.2.2/deps/uv/include -I/Users/andrew/.node-gyp/4.2.2/deps/v8/include -I../node_modules/nan -I../src  -Os -gdwarf-2 -mmacosx-version-min=10.5 -arch x86_64 -Wall -Wendif-labels -W -Wno-unused-parameter -std=gnu++0x -fno-rtti -fno-threadsafe-statics -fno-strict-aliasing -MMD -MF ./Release/.deps/Release/obj.target/midi/src/node-midi.o.d.raw  -c -o Release/obj.target/midi/src/node-midi.o ../src/node-midi.cpp
  c++ -bundle -undefined dynamic_lookup -Wl,-search_paths_first -mmacosx-version-min=10.5 -arch x86_64 -L./Release  -o Release/midi.node Release/obj.target/midi/src/node-midi.o -framework CoreMIDI -framework CoreAudio -framework CoreFoundation
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/midi.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andrew/dev/goddess/midi-goddess/node_modules/midi
gyp ERR! node -v v4.2.2
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm verb unsafe-perm in lifecycle true
npm info midi@0.9.4 Failed to exec install script
npm verb unlock done using /Users/andrew/.npm/_locks/midi-1f0a5f8a662113e7.lock for /Users/andrew/dev/goddess/midi-goddess/node_modules/midi
npm verb stack Error: midi@0.9.4 install: `node-gyp rebuild`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at EventEmitter.emit (events.js:172:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
npm verb stack     at emitTwo (events.js:87:13)
npm verb stack     at ChildProcess.emit (events.js:172:7)
npm verb stack     at maybeClose (internal/child_process.js:818:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid midi@0.9.4
npm verb cwd /Users/andrew/dev/goddess/midi-goddess
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "--verbose" "midi"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! midi@0.9.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the midi@0.9.4 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the midi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls midi
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]
npm verb unbuild node_modules/midi
npm info preuninstall midi@0.9.4
npm info uninstall midi@0.9.4
npm verb unbuild rmStuff midi@0.9.4 from /Users/andrew/dev/goddess/midi-goddess/node_modules
npm info postuninstall midi@0.9.4
npm verb gentlyRm don't care about contents; nuking /Users/andrew/dev/goddess/midi-goddess/node_modules/midi

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrew/dev/goddess/midi-goddess/npm-debug.log
```

**Comment by justinlatimer** [comment]
This isn't a problem with node-midi. The key error is this: ``ld: library not found for -lgcc_s.10.5``

Your build is targeting OSX Minimum Version 10.5, but you don't have the 10.5 libraries installed to link to. Try installing those and rebuilding.

Let me know how it goes!
